name: eomappshabit_track
description: "A lightweight habit tracking app."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_native_splash: ^2.4.7
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.20.2
  flutter_svg: ^2.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    -  assets/images/habittrack_light_960.png
    -  assets/images/habittrack_tagline.png
    -  assets/images/habittrack_tagline_800.png
    -  assets/images/home_icon.svg
    -  assets/images/habittrack_light_circle_600.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#2D2860"
  image:         assets/images/habittrack_light_960.png
  branding:      assets/images/habittrack_tagline_800.png
  branding_mode: bottom               
  fullscreen:    true                
  #! ANDROID 12+ configuration:
  android_12:
    color: "#2D2860" 
    image:        assets/images/habittrack_light_circle_600.png  
    icon_background_color: "#2D2860" 
    branding:      assets/images/habittrack_tagline_800.png