// Mocks generated by Mockito 5.4.6 from annotations
// in habittrack/test/views/settings_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:flutter/material.dart' as _i2;
import 'package:habittrack/viewmodels/settings_viewmodel.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTimeOfDay_0 extends _i1.SmartFake implements _i2.TimeOfDay {
  _FakeTimeOfDay_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsViewmodel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsViewmodel extends _i1.Mock implements _i3.SettingsViewmodel {
  MockSettingsViewmodel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get notificationsBlockedByOS =>
      (super.noSuchMethod(
            Invocation.getter(#notificationsBlockedByOS),
            returnValue: false,
          )
          as bool);

  @override
  bool get notificationsEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#notificationsEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasNotificationsPreferenceBeenSet =>
      (super.noSuchMethod(
            Invocation.getter(#hasNotificationsPreferenceBeenSet),
            returnValue: false,
          )
          as bool);

  @override
  _i2.TimeOfDay get notificationTime =>
      (super.noSuchMethod(
            Invocation.getter(#notificationTime),
            returnValue: _FakeTimeOfDay_0(
              this,
              Invocation.getter(#notificationTime),
            ),
          )
          as _i2.TimeOfDay);

  @override
  bool get themeDark =>
      (super.noSuchMethod(Invocation.getter(#themeDark), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> canEnableNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#canEnableNotifications, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  void setNotificationsBlockedByOS(bool? blocked) => super.noSuchMethod(
    Invocation.method(#setNotificationsBlockedByOS, [blocked]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> setNotifications(bool? notificationsEnabled) =>
      (super.noSuchMethod(
            Invocation.method(#setNotifications, [notificationsEnabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setNotificationTime(int? hours, int? mins) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationTime, [hours, mins]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setThemeDark(bool? useThemeDark) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeDark, [useThemeDark]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
